# You are given two strings s and t.
#
# String t is generated by random shuffling string s and then add one more letter at a random position.
#
# Return the letter that was added to t.
# Example 1:
#
# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added

# Example 2:
#
# Input: s = "", t = "y"
# Output: "y"
def find_the_difference(s, t):
    """
    :type s: str
    :type t: str
    :rtype: str
    """
    for i in range(len(t)):
        if t.count(t[i]) != s.count(t[i]):
            return t[i]


s = ""
t = "y"
print(find_the_difference(s, t))
